### ISSUE TITLE
feat/modalWindowTemplate

### ISSUE THREAD

**Issue by satofumiya** [team-red-2203/workshop-omikuji#10]
やること
モーダルウインドウの表示機能、非表示の実装
デザインを崩してしまっていたので元のデザインへの修正

次にやるべきこと
１、大吉などの結果を配列にする。
２、モーダルウインドウを表示する際にランダムで結果を取得して表示する関数を作成する
３、細かいデザインの修正

**Comment by hirotada-t** [comment]
jsファイルで、
`const buttonClose = document.getElementsByClassName('modalClose')[0];`
の部分は何を取得しているのでしょう？？

**Comment by satofumiya** [comment]
モーダルウィンドウ内「トップに戻る」のリンクの要素を取得しています。
サイトを参考に（ほぼ丸パクリ）作成したのでclassの取得になっていますが、これidでも同じじゃんと思い
最新のコードではidの取得に変更しました。
今日もう少し分かりやすくなるように
コメント編集してみます！ありがとうございます。

**Comment by hirotada-t** [comment]
クローズの部分は未完成でしたね！
失礼しました。
次のプルリクエストで修正よろしくです！
