### ISSUE TITLE
develop/randomData

### ISSUE THREAD

**Issue by hirotada-t** [team-red-2203/workshop-omikuji#14]
# 変更ファイル
- data/data.js
- data/data.csv
- img/item/画像ファイル

# 変更内容
## data.js
- luckyItem配列……ラッキーアイテム名と画像ファイル名を格納しています。乱数を使えばランダムにラッキーアイテムを表示できると思います。
- import_csv関数……csvを読み込み→配列に変換→結果ページに反映の処理を引き受けます。

## data.csv
運勢・画像・説明、それぞれの要素を１まとまりにするためにcsvを使いました。
csvは内容の追加や編集がしやすいので、利便性は良いです。
非同期処理・例外処理・外部データ読み込みと盛りだくさんなので、半ばチャレンジですね。
（この程度なら最初から配列で作ってもｒｙ）

# 今後の課題
下記の課題があるので、現状は動作するようになっていません。
- data.jsでおみくじの結果を記入する処理
- omikuji.jsで`display = 'block'`した後にimport_csv関数を実行
- index.htmlの運勢タイトルや画像に適切なid属性を追加、data.jsの読み込み
- 結果ページをウィンドウのような見た目にする？

**Comment by satofumiya** [comment]
data.jsの扱い方がわからずcsvの読み込みでエラーを吐いている状態です。

ブラウザの検証でのコンソールに出てくるエラー文
data.js:12 Fetch API cannot load ”ローカル環境でのファイルのパス” URL scheme "file" is not supported.
import_csv @ data.js:12
data.js:26 TypeError: Failed to fetch
    at import_csv (data.js:12)
    at HTMLAnchorElement.modalOpen (omikuji.js:33)
エラー文ここまで終わりです。

色々調べたのですが非同期などに関して僕がにわか知識のためよく分からなかったです。
エラー文からfetchでローカルファイルが読み込みできないってことなのかなと思って
色々調べて試したのですがうまくいきませんでした。

**Comment by satofumiya** [comment]
一応できるところをやったのでご報告します。
・ラッキーアイテムの画像を追加しました。それに伴ってデザインの修正を行いました。
・おみくじ結果を記入するためのコードを書きました。それに対応したidをindex.htmlの要素につけました。

あとはdisplay:block;した後にimport_csvを実行できれば完成するかと思います。

**Comment by yoshiryo413** [comment]
あと少し！！！

**Comment by hirotada-t** [comment]
プルリクで修正したのでクローズしますね～

**Comment by hirotada-t** [comment]
> ・ラッキーアイテムの画像を追加しました。それに伴ってデザインの修正を行いました。
> 
> ・おみくじ結果を記入するためのコードを書きました。それに対応したidをindex.htmlの要素につけました。

@satofumiya さん
こちらはローカルで修正して、プルリクエストは送っていないですよね？

**Comment by satofumiya** [comment]
メインの表示する機能がうまくいってなかったのでプルリクはしていないです。
とりあえずdata.isは無視して
Omikuni.jsに仮の結果の配列入れて
ローカルで実装してました。

**Comment by hirotada-t** [comment]
こちら解決したのでクローズします。
