### ISSUE TITLE
top/path

### ISSUE THREAD

**Issue by hirotada-t** [team-red-2203/workshop-omikuji#2]
おみくじの結果ページのpathを間違えていました。
# 対象

 - [ ] css
 - [ ] js

**Comment by tkwonn** [comment]
Issueうまく使えていますね！

ちなみに今やられているみたいに、ちょっとしたイシューを書き込んでおくことにも使えますし、IssueからPull Requestという流れで作成することもできます。

どういう事かと言いますと、
プルリクエストで今「トップページのデザインを変更しました」みたいに文章で送るよりは、ブランチ名で送ったほうがチーム開発の課題が複雑であった場合に検索しやすいです。

やり方としては、

1. 付け加える機能にあったIssue名をつける
→例えば、紙吹雪のエフェクトを実装したいなら、feat/animationというタイトルでIssueを作成。

2. そしてここのコメント欄には内容であったり、注意する点など書いてみてください！

3. 右端のAssigneesで誰にでもアサインすることができます！自分にアサインしても大丈夫です

Issueが作成できたらIssueと同じ名前でブランチを作成し、プルリクエストを送りましょう。
→どのIssueに対してのプルリクかわかりやすくするためです。

Issueとプルリクのリンクの方法は以下のリンクを参考にしてみてください。
https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

また、タイトルをみてわかるように、このIssueの番号が#2なので
#2 
のようにプルリク内で書き込むことでリンクさせることもできます。

いちいちブランチを切らなくてもいいと思うかもしれませんが、練習として余裕があればやってみてください！

**Comment by hirotada-t** [comment]
ありがとうございます、参考になります！
機能や変更内容をIssueに書いて、名前でプルリクと紐付けたほうがスッキリしますね。

早速、プルリクとIssueを名前で紐付けてみました。
試しにもう一つリンクしてみます！
