### ISSUE TITLE
おみくじアプリのアニメーションの追加するかどうかについて

### ISSUE THREAD

**Issue by satofumiya** [team-red-2203/workshop-omikuji#8]
①議題
おみくじアプリのアニメーションを実装するかどうかについて

②現状
ランダムリンクについてのコードを書いた後アニメーションについて色々調べてみました。
（僕の書くコード量思ったより少なく時間余ってたので...）
おみくじの結果を元々のウインドウの上に表示することを表現できそうなモーダルウインドウというものを見つけました。
参考url ->   https://tcd-theme.com/2021/08/javascript-modalwindow.html
実際におみくじアプリに使えるかは、まだ検討不足で正直わかりません。

③相談したいこと
・おみくじのアニメーションを実装するかどうか
・おみくじのアニメーションについてモーダルウインドウ以外に良さそうなものがあるかどうか

これについて意見いただきたいです。よろしくお願いします。

**Comment by yoshiryo413** [comment]
javascriptを使う練習をするならモーダルウインドウを使って良いと思います！！
各の練習にもなりますし、その開発意欲は最高に良きです！！！！
僕は開発に賛成です！

**Comment by satofumiya** [comment]
モーダルウインドウ簡単に実装してみました。
これをいじっていけば実装できそうです。
https://github.com/satofumiya/randomLink.git
以下参考にしたサイトです
モーダルウインドウについて→ https://tcd-theme.com/2021/08/javascript-modalwindow.html
HTMLの要素の変え方 → https://wp-p.info/tpl_rep.php?cat=js-biginner&fl=r13
