### ISSUE TITLE
文字の変数化について

### ISSUE THREAD

**Issue by yoshiryo413** [team-red-2203/workshop-omikuji#9]
議題【文字の変数化】

大吉、中吉,etc...と説明文やラッキーアイテムをjavascrioptで変数化して呼び出せないかなと思ってます！

各画面に文章を逐一書くのはエンジニアとしては、カッコよくないので変数化希望です！
ご確認お願いいたします！！

**Comment by satofumiya** [comment]
モーダルウインドウ作る際に変数にしてもらったほうが実装できる気がしますのでぜひお願いします。

**Comment by hirotada-t** [comment]
画像も、画像名を配列に入れておけば呼び出せるので、トップページとjsファイル+画像だけで完結できるかもですね。
